apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: michal-postgres-sa-anyuid
subjects:
  - kind: ServiceAccount
    name: michal-postgres-sa
    namespace: devops-testing
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io
