prometheus:
  enabled: true
  alertmanager:
    enabled: false
  configmapReload:
    prometheus:
      enabled: true
  kube-state-metrics:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  rbac:
    create: false
  serviceAccounts:
    server:
      create: false
      name: michal-postgres-sa
  server:
    global:
      scrape_interval: 5s
      scrape_timeout: 3s
      evaluation_interval: 30s
    service:
      servicePort: 9090
  extraScrapeConfigs: |
    - job_name: 'michal-prometheus-postgres-exporter-job'
      metrics_path: /metrics
      scrape_interval: 45s
      scrape_timeout:  30s
      static_configs:
        - targets: ['michal-third-chart-prometheus-postgres-exporter.devops-testing']

postgresql:
  enabled: true
  serviceAccount:
    name: michal-postgres-sa
  auth:
    username: testuser
    password: testpass
    postgresPassword: adminpass
  primary:
    securityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
  volumePermissions:
    enabled: false
  shmVolume:
    enabled: false

prometheus-postgres-exporter:
  enabled: true
  rbac:
    create: false
    pspEnabled: false
  serviceAccount:
    create: false
    name: michal-postgres-sa
  config:
    datasource:
      host: michal-third-chart-postgresql.devops-testing
      user: testuser
      password: testpass
      database: postgres
    logLevel: debug
