name: Helm Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.6.3'

    - name: Update Helm Chart Version
      run: |
        sed -i 's/version: .*/version: 1.2.3/' helm/Chart.yaml
        cat helm/Chart.yaml

    - name: Package Helm Chart
      run: |
        helm package helm
        ls -l

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        login-server: ${{ secrets.ACR_URL }}
        username: ${{ secrets.ACR_PUSH_USER }}
        password: ${{ secrets.ACR_PUSH_TOKEN }}

    - name: Set ACR Repository
      run: |
        ACR_REPO="${{ secrets.ACR_URL }}.azurecr.io/helm/michal"
        echo "::set-output name=acr_repo::$ACR_REPO"

    - name: Docker Login to ACR
      run: |
        az acr login --name <your-acr-name>

    - name: Tag and Push Helm Chart to ACR
      run: |
        docker build -t ${{ steps.release.outputs.acr_repo }}:latest .
        docker push ${{ steps.release.outputs.acr_repo }}:latest

    - name: Deploy Helm Release
      run: |
        helm install my-release ${{ steps.release.outputs.acr_repo }}:latest
