name: Helm Chart Release

on:
  push:
    branches:
      - master
    paths:
      - 'helm/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.6.3'

    - name: Bump a Helm Chart Version Locally
      uses: explorium-ai/bump-helm-chart-action@main
      with:
        chart-path: helm/**
        app_version: true
        level: patch


    - name: Update Helm Chart Version
      run: |
        cd helm
        # Assuming your version is a semantic version (e.g., 1.2.3)
        CURRENT_VERSION=$(grep 'version:' Chart.yaml | awk '{print $2}')
        NEW_VERSION="1.2.3"  # Implement your version bumping logic here
        sed -i "s/version: $CURRENT_VERSION/version: $NEW_VERSION/" Chart.yaml

    - name: Package Helm Chart
      run: |
        cd helm
        helm package .

    - name: Log into Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: '${{ secrets.ACR_URL }}'
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Push to ACR
      run: |
        cd helm
        docker push '${{ secrets.ACR_URL }}/helm/michal:latest'
