name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - 'helm/**'

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
         charts_dir: helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
# name: Helm Chart Release

# on:
#   push:
#     branches:
#       - master
#     paths:
#       - 'helm/**'

# jobs:
#   release:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v2
#     - uses: azure/docker-login@v1
#       with:
#         login-server: ${{ secrets.ACR_URL }}
#         username: ${{ secrets.ACR_PUSH_USER }}
#         password: ${{ secrets.ACR_PUSH_TOKEN }}


#     - name: Set up Helm
#       uses: azure/setup-helm@v1
#       with:
#         version: 'v3.6.3'

#     - name: Run chart-releaser
#       uses: helm/chart-releaser-action@v1.6.0
#       with:
#         charts_dir: helm
# #        config: cr.yaml
#       env:
#         CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

#     # - name: Bump Helm Chart Version
#     #   run: |
#     #     cd helm
#     #     helm version
#     #     helm bump chart

#     # - name: Package Helm Chart
#     #   run: |
#     #     cd helm
#     #     helm package .

#     # - name: Upload to ACR
#     #   uses: Azure/docker-login@v1
#     #   with:
#     #     login-server: ${{ secrets.ACR_URL }}
#     #     username: ${{ secrets.ACR_PUSH_USER }}
#     #     password: ${{ secrets.ACR_PUSH_TOKEN }}

#     # - name: Push to ACR
#     #   run: |
#     #     cd helm
#     #     docker push ${{ secrets.ACR_URL }}/helm/michal-test:latest'
